fix(mappe)
EndPass-Game/programmazione pull request #71
Opened 2022-09-02 16:20 UTC by giospada

## Descrizione 

## Contesto

[PG-1](https://flecart.atlassian.net/browse/PG-1)

## Screenshots

2022-09-02 16:20 UTC, giospada commented
better now

2022-09-03 19:41 UTC, Flecart requested changes
1. fix di 2.txt
2. Aggiornare la docs di loader-handler

2022-09-03 19:41 UTC, Flecart commented on assets/2.txt
> +6 30 41
è buggata questa riga, dovrebbero esserci 2 numeri

2022-09-04 08:26 UTC, Flecart approved these changes

2022-09-04 08:31 UTC, merged