feat (loader): refactored artifacts and enemies inside map
EndPass-Game/programmazione pull request #76
Opened 2022-09-04 17:05 UTC by Ruggi54

## Descrizione 
Modificato nemici all'interno della mappa e gli artefatti ora danno vita differente in base anche alla difficoltà del livello
Manca da moficiare il file di python che ti crea la mappa per come è vista, non lo so fare io, non so se basta runnarlo

## Contesto
[PG-1](https://flecart.atlassian.net/browse/PG-1)

2022-09-04 20:29 UTC, Flecart requested changes
Un livello è da fixare, il resto mi sembra apposto

2022-09-04 20:29 UTC, Flecart commented on assets/5.txt
> +8 20
Questo nemico qui è sopra un muro, bisogna fixare

2022-09-05 07:05 UTC, giospada commented
così ho anch'io il badge di GITHUB

2022-09-05 13:50 UTC, Flecart commented
@giospada non te lo da così lel

2022-09-05 13:52 UTC, merged